# Generated by Django 3.1.1 on 2020-09-15 21:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=None)),
            ],
        ),
    ]
